store:
    # data-only container
    image: postgres:9.5-alpine # reuse postgres container
    volumes:
        - /var/lib/postgresql/9.5/data
    command: "true"

postgres:
    image: postgres:9.5-alpine
    ports:
        - "5432:5432" # random available host port will be chosen, same as -P
    volumes_from:
        - store # connect postgres and the data-only container
    environment:
        - POSTGRES_PASSWORD=Igor1993
        - POSTGRES_DB=english_city
        - PGDATA=/var/lib/postgresl/9.5/data

go:
    build: .
    links:
        - postgres:db # [other container]:[alias in this container]
        # this will create environment variables in the go container
        # with ip and port info for the postgres container
        # also creates entries in /etc/hosts with ip info
    ports:
        - "8080:8080" # this is port i'm exposing in the container
    environment:
        - PORT=8080
